# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
---
builds:
  - main: "./main.go"
    binary: vend
    ldflags:
      - -X vend/internal/update.Version={{ .Version }}
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  prerelease: auto

universal_binaries:
  - replace: false
    mod_timestamp: "{{ .CommitTimestamp }}"

brews:
  - name: vend
    homepage: https://github.com/tsukinoko-kun/vend
    description: Manage external sources easily
    repository:
      owner: tsukinoko-kun
      name: homebrew-tap
    commit_author:
      name: tsukinoko-kun
      email: gh@frankmayer.dev
